### ISSUE TITLE
[MD+] The Lion King test results

### ISSUE THREAD

**Issue by ArcadeTV** [ArcadeTV/msuplus-tracker#10]
Please report any issues in separate tickets.

If you tested the game and had no issues, report here with the following info:
* [ ] Platform
* [ ] Game completed?
* [ ] Tested extra stuff: pause, sound test etc.

Using cheats is totally fine while testing.

**Comment by landstalker01** [comment]
Hi ArcadeTV, thank you for making the Lion King Patch. Until now, I discovered one minor issue:

Platform: RetroArch (Genesis GX Plus)
error description: track 18 is not playing with the 05.04.2023 patch (I also replaced the track from the soundpack and double checked the cue-file)
Game completed?: no

Thank you in advance.

**Comment by ArcadeTV** [comment]
Thank you for your feedback!
Since 2 users reported the game as 'good', I will add the finishing touches and promote the patch to 'complete'.

**Comment by ArcadeTV** [comment]
Added the pause/resume functions and patch is promoted to `Release Candidate`

https://github.com/ArcadeTV/msuplus-tracker/blob/main/patches/LionKing_MDplus(20230409-070536).zip
