### ISSUE TITLE
[MD+] Marvel Land

### ISSUE THREAD

**Issue by Relikk** [ArcadeTV/msuplus-tracker#14]
In Retroarch there are a couple of issues, currently.

First thing I noticed, in the sound test is that in the stock ROM the "B" button stops the music. In the MD+ patched ROM this doesn't work. The "B" button doesn't stop the music.

The game also freezes on a black screen if you let the first gameplay demo run. It happens straight after it.

**Comment by ArcadeTV** [comment]
Oh yes, acknowledged. My testing was crap in the first place - I used the test-tracks and didn't notice the issues, but they're all over the place. I'll look into this.

**Comment by ArcadeTV** [comment]
Here's a new patch that adds music stopping and a logic-fix to play the correct track:

https://github.com/ArcadeTV/msuplus-tracker/raw/main/patches/MarvelLand_MDplus(20230420-220221).zip

**Comment by ArcadeTV** [comment]
[21_namco.zip](https://github.com/ArcadeTV/msuplus-tracker/files/11290817/21_namco.zip)

I've updated the patch again:

https://github.com/ArcadeTV/msuplus-tracker/raw/main/patches/MarvelLand_MDplus(20230421-001735).zip

This introduces a "NAMCO" voice on the namco logo screen (replaces SEGA voice, track 21), as well as it fixes another problem with sounds not stopping when dying. Unfortunately it adds another issue, that's the dying sfx is gone, but I'll investigate why this is happening.

**Comment by ArcadeTV** [comment]
This should be the first ReleaseCandidate RC1:
https://github.com/ArcadeTV/msuplus-tracker/raw/main/patches/MarvelLand_MDplus(20230421-113502).zip
* re-added and fixed intro
* all issues fixed and tested

Will close the issue as soon as you say it's good now. ✌️

**Comment by Relikk** [comment]
Seems fine now. Thanks.

**Comment by ArcadeTV** [comment]
Ur very welcome, thanks for testing.

**Comment by MegaRyeGuy** [comment]
A couple of bugs detected.  Not sure if you guys found this yet.  

On MegaSD (original) in Mega SG, Marvel land starts up, but no MD+ intro sound or Namco sound.  It does play music during story, but freezes to a black screen while entering level one.  Hard crash.  I have to power my system off, and then on again.

In Retroarch with GenesisPlusGX core - No intro sound or Namco sound.  The first level loads normally, along with music.

**Comment by Relikk** [comment]
That could be discrepancies with file names and what is contained in the CUE file, as there were changes after the most recent patch. When did you download the audio?

I include silent tracks for Sega and the MD+ jingle by default (you can acquire them proper from the jingles folder), but I did include a Namco track in the latest upload. Make sure you're using that one.

**Comment by MegaRyeGuy** [comment]
Oh, well that explains the silent MD+ jingle.  I got the audio from the mega folder that was linked.  Downloaded the most recent.

**Comment by MegaRyeGuy** [comment]
I swapped out the placeholder .wav files with the jingle .wav files.  This worked with all MD+ I have assembled except for this one.  Still no MD+ or Sega jingles.  Is this perhaps still being worked on?  Sorry if I have jumped the gun.

**Comment by ArcadeTV** [comment]
There is no SEGA logo in Marvel Land, but a NAMCO intro, the one with the opening curtains.
In theory there is a 21_namco.wav file in the pack. 
If you have all files listed in the cue sheet present and renamed the cue exactly as your rom it should work.

**Comment by Relikk** [comment]
Assuming you're on Windows, open the CUE file that you got from the latest audio upload with notepad and check that the filenames match. Everything should be fine until you get down to track 21 and 22. That's where your issues seem to lie.

**Comment by MegaRyeGuy** [comment]
Thank you both.  I am new to editing .cue files.  Looks like I failed to capitalize "Namco.wav" and that was enough to cause the game to crash on the MegaSD.  Marvel land appears to be booting up the same on hardware and emu, with all jingles and story music in place.

**Comment by ArcadeTV** [comment]
Yes, the CUE represents a CD image and has to be valid. This means:
* specified files have to be present
* syntax must be correct
* overall size must not exceed ~700MB (at least in MD+/RetroArch this must be the case)

**Comment by MegaRyeGuy** [comment]
Excellent.  I'll test my files with CDmage now.  Thank you.

**Comment by MegaRyeGuy** [comment]
![Screenshot 2023-04-23 153912](https://user-images.githubusercontent.com/113917283/233865143-5e27bea3-fdc8-4297-8334-8173e95d082f.png)

**Comment by MegaRyeGuy** [comment]
CDmage is giving me this error with all of the MD+ I assembled.  Is this a common error?

**Comment by ArcadeTV** [comment]
Yes, since all wave files are not padded to a real cd sector size, CDmage complains about it. You could ignore this or make an audio cd image with e.g. UltraISO, which applies the padding automatically and then rip and use these tracks. 
If your cue and files would have other issues, CDmage would have told you, so you're good to go.

**Comment by Relikk** [comment]
The CUE files also contain commands that are exclusive to the MD+ format and wouldn't be standard, like LOOP. I wouldn't worry about it. Marvel Land is the only audio pack I've updated, and I know the rest of the packs I've done are all fine with regard to naming. So if you want to swap out any tracks just make sure they're numbered and named the same as the original file, otherwise you'll have to edit the CUE file manually in notepad.

**Comment by MegaRyeGuy** [comment]
Well, that's a relief.  Thanks for the quick response.
