### ISSUE TITLE
[MD+] Insector X

### ISSUE THREAD

**Issue by Relikk** [ArcadeTV/msuplus-tracker#15]
The music after killing the boss at the end of a round continues to play until the next round starts...

https://user-images.githubusercontent.com/1951885/233865885-d42785d2-8641-49b5-bc61-23bbd8bd9499.mp4

Judging by this playthrough...

https://www.youtube.com/live/mZzNTJ3vWfA?feature=share&t=277

...the music should fade out as soon as the boss starts to die.

**Comment by ArcadeTV** [comment]
Thanks for the video and youtube reference!

Here's an updated patch that should do the trick: https://github.com/ArcadeTV/msuplus-tracker/blob/main/patches/InsectorX_MDplus(20230424-073717).zip

**Comment by ArcadeTV** [comment]
BTW, here are some cheats: 
https://gamehacking.org/game/15267

**Comment by Relikk** [comment]
Latest patch has fixed that issue. Cheers!
