### ISSUE TITLE
Request: NHL 94 without audio skip

### ISSUE THREAD

**Issue by tomillr** [ArcadeTV/msuplus-tracker#19]
Hey there,

would it be possible to patch the Sega CD-version of NHL 94 so that the looping audio doesn't skip? The game uses red book audio track during matches to play crowd noises and music. Unfortunately, whenever the game skips tracks, the audio cuts out and it sounds like the entire station all went to the bathroom at the same time. Otherwise this is the best version of maybe the best sports game ever made.

Best
Tom

**Comment by ArcadeTV** [comment]
Hello Tom, 
I'm afraid creating a patch for a SegaCD game is beyond my skills. I'm sure it would be possible though by messing with the game's sound driver and disabling seek-time-emulation on MegaED.
