### ISSUE TITLE
[MSU-MD] Flicky

### ISSUE THREAD

**Issue by MegaRyeGuy** [ArcadeTV/msuplus-tracker#2]
On Mega SD in Analogue Mega SG:

1) Game startup: After MSU-MD logo, the "SEGA" voice sample plays twice.  Once before Sega logo, and once at Sega logo.

2) Death sound: There is a short, truncated sound that plays immediately after the death sound and animation finish.

3) Level start: At the start of a new level, the music will sometimes start, and then restart a few seconds later.

4) Level complete:  Occasionally the audio will get hung up while playing the "level complete" sound.  It sounds like the system is freezing up for about one second, and then the game resumes.

5) Bonus round: The "level complete" music will play in the middle of the bonus round.  It will then resume the bonus music, and finally play the "level complete" music at the end.

**Comment by ArcadeTV** [comment]
weird issues :-/
I will compile an MD+ version next without changing any locations where I hooked in.
Excited to see if this results in the same bahaviour.
Thanks for the report!

**Comment by MegaRyeGuy** [comment]
> weird issues :-/ I will compile an MD+ version next without changing any locations where I hooked in. Excited to see if this results in the same bahaviour. Thanks for the report!

My pleasure, I believe I will have time to test one game each morning.  In regards to Flicky, I have a feeling that the MD+ will operate better on the MegaSD.  Not to say that MSU-MD are inferior, they usually play fine.  But the MD+ seem more predictable on MegaSD.

**Comment by ArcadeTV** [comment]
Here's an MD+ version 
[Flicky_MDplus(20230406-224209).zip](https://github.com/ArcadeTV/msuplus-tracker/files/11174289/Flicky_MDplus.20230406-224209.zip)

The soundPack is not so different from the MSU-MD one:
* The intro jingle was changed to the md+ variant
* All Loop-Instructions went into the .cue file

[Flicky MD+ soundPack](https://drive.google.com/file/d/1z-hZ2HvJWsK005DkZFDcoE905Kf9NvXz/view?usp=share_link)

pls remember to rename the .cue file's base filename the same as your rom file.

**Comment by MegaRyeGuy** [comment]
Thanks for whipping together the MD+ version so quickly.  I'll assemble and test it now.

**Comment by ArcadeTV** [comment]
Would be nice if you could point TO to the issue:
"Looping with PLAYOF command results in unpredictable playback on MegaSD"

see https://github.com/krikzz/msu-md >> 0x1A PLAYOF

They can test the MSU-MD version against the MD+ one.
