### ISSUE TITLE
[MSU-MD] Garfield: Caught in the Act

### ISSUE THREAD

**Issue by avegee24** [ArcadeTV/msuplus-tracker#22]
hey uh i've been looking for a patch of this game for quite a long time and i've never found one, so could you please do it?

you're better off using the PC version soundtrack, although i've heard an arrangement of one song is 2 parts from the MD version "squished" together

**Comment by avegee24** [comment]
by the way it uses GEMS

**Comment by ArcadeTV** [comment]
I did this in April 2021 ^^
[Garfield_MSU-MD_v0.1_ArcadeTV.zip](https://github.com/ArcadeTV/msuplus-tracker/files/13625821/Garfield_MSU-MD_v0.1_ArcadeTV.zip)

I have no idea what the latest status was for this and zero time to dig into it if there are issues.

**Comment by avegee24** [comment]
GREAT THANKS
