### ISSUE TITLE
[MD+] Langrisser 2 (aka Warsong2) patch request

### ISSUE THREAD

**Issue by Mengze-L** [ArcadeTV/msuplus-tracker#25]
Hi @ArcadeTV ,

As known you are busy, is it possible to get your help to find out the routine location in the rom to be patch for Langrisser2? If so, I can try to create my first MD+ patch. I did disassembling on the rom but have not yet figure out where I should start from. Thanks for your reply and have good time!

**Comment by ArcadeTV** [comment]
I invited you to Langrisser 2 repo. It was adandoned long ago and may have issues - hope it helps anyway. I believe there's another patch out there that works correctly.

**Comment by Mengze-L** [comment]
Very appreciate! let me look into it
