### ISSUE TITLE
[MD+] Joe & Mac "Game Over"

### ISSUE THREAD

**Issue by Relikk** [ArcadeTV/msuplus-tracker#3]
The "Game Over" track (track 10) doesn't play, but I'm only assuming this track is mapped based on your New Joe & Mac sound pack, which includes a Game Over track.

**Comment by ArcadeTV** [comment]
"Get Ready" and "Game Over" are silent in the game. I planned ahead and added the game over music to the soundpack.
The locations for patching are already found, so in the next version you may make a wish - only game over or both game over and get ready.
I dunno if the arcade had a get ready tune or if this could be derived from what the existing music.

**Comment by Relikk** [comment]
> I dunno if the arcade had a get ready tune or if this could be derived from what the existing music.

It didn't. It's the same as the Mega Drive version. There are no get ready and no game over jingles.

> The locations for patching are already found, so in the next version you may make a wish - only game over or both game over and get ready.

The only drawback is that the game over screen itself doesn't last long. About 2 and a half seconds. Both game over jingles (New J & M and arcade) are probably double that amount of time. Otherwise I'd go for only game over.

**Comment by ArcadeTV** [comment]
> The only drawback is that the game over screen itself doesn't last long. About 2 and a half seconds. Both game over jingles (New J & M and arcade) are probably double that amount of time. Otherwise I'd go for only game over.

I can fix that ^^
I'll add the appropriate amount of frames to wait until the track finishes.

**Comment by ArcadeTV** [comment]
[JoeMac_PyronECv2_MDplus(20230406-215946).zip](https://github.com/ArcadeTV/msuplus-tracker/files/11174083/JoeMac_PyronECv2_MDplus.20230406-215946.zip)

Here's an updated Patch. Needs Pyron's enhancement applied first.

* [x] Added a good amount of time to the game over screen
* [x] Music will just fade out on Get Ready screen
* [x] Track 10 is played on Game Over screen

pls note: I had a wrong filename in my soundPack. See .cue file for correction. No re-download neccessary, just rename the wave files according to the .cue.

Would be nice if you could manage both soundPacks, Arcade and NewJoe&Mac.
Thanks!

**Comment by Relikk** [comment]
While playing through the latest patch to check out the audio balancing on both sound packs, there were no issues.
