### ISSUE TITLE
[MD+] Flicky

### ISSUE THREAD

**Issue by MegaRyeGuy** [ArcadeTV/msuplus-tracker#4]
Hardware: MegaSD in Analogue Mega SG.

The death sound plays in mono. (right speaker only)

Note: No other issues to report, as all other sounds and music play perfectly.

**Comment by ArcadeTV** [comment]
The audio was recorded from the SEGA CD version, so I assume this to be identical to real hardware.
I can see that the channels are not well balanced, but could be an intended effect.

![Flicky_Player-Down-Audition](https://user-images.githubusercontent.com/26868804/230499882-06f1b0ef-d50c-40e8-a262-842bece844a8.jpg)

Fixing this is easy, so I will re-upload the soundPack.

**Comment by ArcadeTV** [comment]
https://drive.google.com/file/d/1_n_eJB_-t8gXRQCo6NZ5HiE85InDml-G/view?usp=share_link

**Comment by MegaRyeGuy** [comment]
Wonderful.  I will test again tonight.  Happy to see how well this one came out.  It's my Wife's favorite game.

**Comment by MegaRyeGuy** [comment]
Fixed.  Ready to publish.  Nice work.

**Comment by ArcadeTV** [comment]
> Fixed. Ready to publish. Nice work.

I will green-light a game as soon as at least 2 users claim that the game is bug-free.

> Happy to see how well this one came out. It's my Wife's favorite game.

Glad to hear that - now, add some Bubble Bobble music to the soundPack and enjoy your spare time ^^

**Comment by MegaRyeGuy** [comment]
Bubble Bobble would be a great fit.  :)

**Comment by MegaRyeGuy** [comment]
Just a quick note.  My wife and I were playing Flicky MD+ on a different Tv with a slightly different speaker configuration.  Two things happened.  Just once, the death sound glitched out, but we couldn't reproduce the glitch after about five games.  And lastly, the death sound seems to be louder in the left speaker now.  I believe this is partially my fault, and tomorrow when I test another game I will make sure to use my studio headphones instead of speakers. I hope I didn't waste too much of your time with the audio correction and I hope I didn't introduce this new glitch.

**Comment by MegaRyeGuy** [comment]
Okay, I just made another playthrough with my studio headphones and I think the death sound is perfectly balanced.  It sounds great.

**Comment by ArcadeTV** [comment]
> I hope I didn't introduce this new glitch.

Since I only edited the wave file there's no way it could affect the program.

**Comment by MegaRyeGuy** [comment]
It was my MegaSD cartridge.  It needed a little cleaning.  All good now.
